name: CI tests
on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.19.x
          - 1.20.x
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y squashfs-tools

      - name: Update Go modules
        run: make update-gomod

      - name: Static analysis
        run: make static-analysis

      - name: Test
        run: make check
